### ISSUE TITLE
Error message and dead server

### ISSUE THREAD

**Issue by deanmaunder** [softwareCobbler/luceedebug#68]
We have recently migrated from Application.cfm to Application.cfc and the debugger is now throwing an error we havent seen before.  The server starts up ok, and we can get to the main page, but when I try to log in (which is done via a series of getPageContext.forward() calls), we get the following error, then the server either hangs, or I get logged out.  Sometimes I can log back in and click around, but eventually the server will hang.

lucee-1                | [INFO ] 16 Nov 2024 14:55:38.493 runwar.context: Page abort detected! /index.cfm
lucee-1                | [INFO ] 16 Nov 2024 14:55:38.613 runwar.context: Page abort detected! /support/index.cfm
lucee-1                | [DEBUG] 16 Nov 2024 14:55:38.617 runwar.server: requested: 'http://localhost:8080/index.cfm?event=applications.defaultSearch'
lucee-1                | *** java.lang.instrument ASSERTION FAILED ***: "!errorOutstanding" with message transform method call failed at src/java.instrument/share/native/libinstrument/JPLISAgent.c line: 876
lucee-1                | *** java.lang.instrument ASSERTION FAILED ***: "!errorOutstanding" with message transform method call failed at src/java.instrument/share/native/libinstrument/JPLISAgent.c line: 87
lucee-1                | OpenJDK 64-Bit Server VM warning: Potentially dangerous stack overflow in ReservedStackAccess annotated method org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(J)Ljava/lang/Object; [1]
lucee-1                | OpenJDK 64-Bit Server VM warning: Potentially dangerous stack overflow in ReservedStackAccess annotated method org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(J)Ljava/lang/Object; [1]
lucee-1                | OpenJDK 64-Bit Server VM warning: Potentially dangerous stack overflow in ReservedStackAccess annotated method org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(J)Ljava/lang/Object; [1]
lucee-1                | OpenJDK 64-Bit Server VM warning: Potentially dangerous stack overflow in ReservedStackAccess annotated method org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(J)Ljava/lang/Object; [1]

Anything I can do to help troubleshoot this?  I have JDKMC connected, but Im not overly familiar with it so not sure what I need to do to extract the information you might need.

This is happening without the debugger connected in vscode, if I try to do that once this problem has occured, I get this:

lucee-1                | [ERROR] 16 Nov 2024 15:35:32.149 runwar.context: [SEVERE] 2024-11-16T15:35:32.145+1100 - Internal error: Could not initialize class java.util.concurrent.ForkJoinPool
lucee-1                | 
lucee-1                | [ERROR] 16 Nov 2024 15:35:32.153 runwar.context: java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: Could not initialize class java.util.concurrent.ForkJoinPool
lucee-1                | [ERROR] 16 Nov 2024 15:35:32.153 runwar.context:       at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
lucee-1                | [ERROR] 16 Nov 2024 15:35:32.153 runwar.context:       at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
lucee-1                | [ERROR] 16 Nov 2024 15:35:32.153 runwar.context:       at luceedebug_shadow.org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor$1.get(ConcurrentMessageProcessor.java:54)
lucee-1                | [ERROR] 16 Nov 2024 15:35:32.153 runwar.context:       at luceedebug_shadow.org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor$1.get(ConcurrentMessageProcessor.java:50)
lucee-1                | [ERROR] 16 Nov 2024 15:35:32.153 runwar.context:       at luceedebug.DapServer.createForSocket(DapServer.java:144)
lucee-1                | [ERROR] 16 Nov 2024 15:35:32.154 runwar.context:       at luceedebug.coreinject.DebugManager.lambda$spawnWorker$0(DebugManager.java:75)
lucee-1                | [ERROR] 16 Nov 2024 15:35:32.154 runwar.context:       at java.base/java.lang.Thread.run(Thread.java:840)
lucee-1                | [ERROR] 16 Nov 2024 15:35:32.154 runwar.context: Caused by: java.lang.NoClassDefFoundError: Could not initialize class java.util.concurrent.ForkJoinPool
lucee-1                | [ERROR] 16 Nov 2024 15:35:32.154 runwar.context:       at java.base/java.util.concurrent.CompletableFuture.<clinit>(CompletableFuture.java:431)
lucee-1                | [ERROR] 16 Nov 2024 15:35:32.154 runwar.context:       at luceedebug.DapServer.initialize(DapServer.java:174)
lucee-1                | [ERROR] 16 Nov 2024 15:35:32.154 runwar.context:       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
lucee-1                | [ERROR] 16 Nov 2024 15:35:32.154 runwar.context:       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
lucee-1                | [ERROR] 16 Nov 2024 15:35:32.154 runwar.context:       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
lucee-1                | [ERROR] 16 Nov 2024 15:35:32.154 runwar.context:       at java.base/java.lang.reflect.Method.invoke(Method.java:569)
lucee-1                | [ERROR] 16 Nov 2024 15:35:32.154 runwar.context:       at luceedebug_shadow.org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$recursiveFindRpcMethods$0(GenericEndpoint.java:65)
lucee-1                | [ERROR] 16 Nov 2024 15:35:32.154 runwar.context:       at luceedebug_shadow.org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:128)
lucee-1                | [ERROR] 16 Nov 2024 15:35:32.154 runwar.context:       at luceedebug_shadow.org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:271)
lucee-1                | [ERROR] 16 Nov 2024 15:35:32.154 runwar.context:       at luceedebug_shadow.org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:201)
lucee-1                | [ERROR] 16 Nov 2024 15:35:32.154 runwar.context:       at luceedebug_shadow.org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:185)
lucee-1                | [ERROR] 16 Nov 2024 15:35:32.154 runwar.context:       at luceedebug_shadow.org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:97)
lucee-1                | [ERROR] 16 Nov 2024 15:35:32.154 runwar.context:       at luceedebug_shadow.org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:114)
lucee-1                | [ERROR] 16 Nov 2024 15:35:32.154 runwar.context:       at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
lucee-1                | [ERROR] 16 Nov 2024 15:35:32.155 runwar.context:       at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
lucee-1                | [ERROR] 16 Nov 2024 15:35:32.155 runwar.context:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
lucee-1                | [ERROR] 16 Nov 2024 15:35:32.155 runwar.context:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
lucee-1                | [ERROR] 16 Nov 2024 15:35:32.155 runwar.context:       ... 1 more
lucee-1                | [INFO ] 16 Nov 2024 15:35:32.156 runwar.server: Stopping server 'QA-782c55131543'
lucee-1                | [DEBUG] 16 Nov 2024 15:35:32.179 runwar.server: All deployments undeployed and underlying Undertow servers stopped
lucee-1                | [INFO ] 16 Nov 2024 15:35:32.195 runwar.server: Stopped server
lucee-1                | [DEBUG] 16 Nov 2024 15:35:32.198 runwar.server: Stopped listening for stop password.
lucee-1 exited with code 1

**Comment by zspitzer** [comment]
Please always include the software versions in your stack in bug reports 😃

**Comment by softwareCobbler** [comment]
Yes the (JDK version, lucee version, luceedebug version) tuple is always helpful.

I was able to build a similar reproduction (native JPLIS assertion failures), and the issue was a confluence of 2 problems:
  - System.out not classloaded by the time the agent starts transforming classes (and trying to println I think causing a stackoverflow)
  - outdated ASM lib not able to read classfile versions 65+
  
So the ASM lib would throw "can't read this classfile" and then we try to print that, and System.out.println bombs out and the whole thing just keels over.

Both of these issues are fixed on https://github.com/softwareCobbler/luceedebug/tree/jplis-error, can you build that and give it a go? I'm not 100% that the classfile versioning issue is the problem on your side, but the agent should now at least print whatever exception is causing grief.

**Comment by deanmaunder** [comment]
Oops, knew I forgot something....
BOX_SERVER_JVM_JAVAVERSION=openjdk17_jdk_aarch64_linux
BOX_SERVER_APP_CFENGINE=lucee@5.4.6+9
luceedebug-2.0.14
:)

I built the jar from that branch, but I didnt see any new errors, just the same one I posted above.  

`lucee-1                | OpenJDK 64-Bit Server VM warning: Potentially dangerous stack overflow in ReservedStackAccess annotated method org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(Ljava/time/Duration;)Ljava/lang/Object; [1]`

I did find something interesting...
I set
`this.sessionstorage        = "sessioncache";`
In Application.cfc, sessioncache being pointed a local Redis container via .cfconfig.json
If I set
`this.sessionstorage        = "memory";`
I don't see the same problems occuring.

Using redis.extension-3.0.0.55-SNAPSHOT, also tried the Ortus Redis extension (3.3.1+70), but that gave me a stack overflow error (attached)

[stackoverflow.txt](https://github.com/user-attachments/files/17788195/stackoverflow.txt)

**Comment by softwareCobbler** [comment]
The stackoverflow appears as roughly:
 - push cf frame on stack
 - initialize debug frame tracker; read session scope
 - lucee deserializes some java object from wherever session scope is stored
 - deserialization recursively invokes "create new /app/LIS/util/envHelper.cfc"
 - creating new object pushes a new cf frame
 - recurse
 
You might be able to work around this with the following patch:

```
- this.session     = getScopelikeOrNull(() -> pageContext.getApplicationContext().isSetSessionManagement() ? pageContext.sessionScope() : null);
+ this.session     = null;
```

To aid further investigation, can you provide a minimal reproduction in a docker compose setup?

**Comment by deanmaunder** [comment]
That has indeed resolved the stack trace problem, and I can still see the contents of `session` by adding a watch.

It seems to be related to something happening when we put a component into the session scope, because I can hit the login page and see the session content fine, but once I login, which is where we put the User component into the session scope, that is where the stacktrace happens, at least when using the Ortus extension.

Also tested with the patch using the Lucee Redis extension and no problem there also.

I have noticed some recursion in the variables scope, not sure if its related, it still shows up when everything is working ok so I wasnt sure if it was just supposed to be this way.
![image](https://github.com/user-attachments/assets/ec74288a-f640-42ae-b9f7-4ce8117fbb99)


I will try to get a repro case up later today.

**Comment by deanmaunder** [comment]
Ive got a repro case here https://github.com/deanmaunder/luceedebug-issue
Its using the Ortus cache extension because that seems to cause more problems than the Lucee Redis (or the problems are more obvious)
Let me know if I can help further.

**Comment by softwareCobbler** [comment]
Thanks for the repro. Should be good on master branch now.

**Comment by deanmaunder** [comment]
Thanks!
